/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAclRouteImport } from './routes/_authenticated/acl'
import { Route as AuthenticatedApiKeysRouteImport } from './routes/_authenticated/api-keys'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAuthProvidersRouteImport } from './routes/_authenticated/auth-providers'
import { Route as AuthenticatedAutoSubscriptionsRouteImport } from './routes/_authenticated/auto-subscriptions'
import { Route as AuthenticatedBlacklistRouteImport } from './routes/_authenticated/blacklist'
import { Route as AuthenticatedBrokerConfigRouteImport } from './routes/_authenticated/broker-config'
import { Route as AuthenticatedNodesRouteImport } from './routes/_authenticated/nodes'
import { Route as AuthenticatedPublishRouteImport } from './routes/_authenticated/publish'
import { Route as AuthenticatedRetainsRouteImport } from './routes/_authenticated/retains'
import { Route as AuthenticatedRoutesRouteImport } from './routes/_authenticated/routes'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedWebhooksRouteImport } from './routes/_authenticated/webhooks'
import { Route as AuthenticatedBridgesIndexRouteImport } from './routes/_authenticated/bridges/index'
import { Route as AuthenticatedBridgesPluginRouteImport } from './routes/_authenticated/bridges/$plugin'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients/$clientId'
import { Route as AuthenticatedPluginsIndexRouteImport } from './routes/_authenticated/plugins/index'
import { Route as AuthenticatedPluginsNodeIdPluginRouteImport } from './routes/_authenticated/plugins/$nodeId/$plugin'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAclRoute = AuthenticatedAclRouteImport.update({
  id: '/acl',
  path: '/acl',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiKeysRoute = AuthenticatedApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuthProvidersRoute =
  AuthenticatedAuthProvidersRouteImport.update({
    id: '/auth-providers',
    path: '/auth-providers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutoSubscriptionsRoute =
  AuthenticatedAutoSubscriptionsRouteImport.update({
    id: '/auto-subscriptions',
    path: '/auto-subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlacklistRoute = AuthenticatedBlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrokerConfigRoute =
  AuthenticatedBrokerConfigRouteImport.update({
    id: '/broker-config',
    path: '/broker-config',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNodesRoute = AuthenticatedNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPublishRoute = AuthenticatedPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRetainsRoute = AuthenticatedRetainsRouteImport.update({
  id: '/retains',
  path: '/retains',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutesRoute = AuthenticatedRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWebhooksRoute = AuthenticatedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBridgesIndexRoute =
  AuthenticatedBridgesIndexRouteImport.update({
    id: '/bridges/',
    path: '/bridges/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBridgesPluginRoute =
  AuthenticatedBridgesPluginRouteImport.update({
    id: '/bridges/$plugin',
    path: '/bridges/$plugin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPluginsIndexRoute =
  AuthenticatedPluginsIndexRouteImport.update({
    id: '/plugins/',
    path: '/plugins/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPluginsNodeIdPluginRoute =
  AuthenticatedPluginsNodeIdPluginRouteImport.update({
    id: '/plugins/$nodeId/$plugin',
    path: '/plugins/$nodeId/$plugin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/acl': typeof AuthenticatedAclRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/auth-providers': typeof AuthenticatedAuthProvidersRoute
  '/auto-subscriptions': typeof AuthenticatedAutoSubscriptionsRoute
  '/blacklist': typeof AuthenticatedBlacklistRoute
  '/broker-config': typeof AuthenticatedBrokerConfigRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/retains': typeof AuthenticatedRetainsRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/bridges/$plugin': typeof AuthenticatedBridgesPluginRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/bridges/': typeof AuthenticatedBridgesIndexRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/plugins/': typeof AuthenticatedPluginsIndexRoute
  '/plugins/$nodeId/$plugin': typeof AuthenticatedPluginsNodeIdPluginRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/acl': typeof AuthenticatedAclRoute
  '/api-keys': typeof AuthenticatedApiKeysRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/auth-providers': typeof AuthenticatedAuthProvidersRoute
  '/auto-subscriptions': typeof AuthenticatedAutoSubscriptionsRoute
  '/blacklist': typeof AuthenticatedBlacklistRoute
  '/broker-config': typeof AuthenticatedBrokerConfigRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/publish': typeof AuthenticatedPublishRoute
  '/retains': typeof AuthenticatedRetainsRoute
  '/routes': typeof AuthenticatedRoutesRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/webhooks': typeof AuthenticatedWebhooksRoute
  '/': typeof AuthenticatedIndexRoute
  '/bridges/$plugin': typeof AuthenticatedBridgesPluginRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/bridges': typeof AuthenticatedBridgesIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/plugins': typeof AuthenticatedPluginsIndexRoute
  '/plugins/$nodeId/$plugin': typeof AuthenticatedPluginsNodeIdPluginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/acl': typeof AuthenticatedAclRoute
  '/_authenticated/api-keys': typeof AuthenticatedApiKeysRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/auth-providers': typeof AuthenticatedAuthProvidersRoute
  '/_authenticated/auto-subscriptions': typeof AuthenticatedAutoSubscriptionsRoute
  '/_authenticated/blacklist': typeof AuthenticatedBlacklistRoute
  '/_authenticated/broker-config': typeof AuthenticatedBrokerConfigRoute
  '/_authenticated/nodes': typeof AuthenticatedNodesRoute
  '/_authenticated/publish': typeof AuthenticatedPublishRoute
  '/_authenticated/retains': typeof AuthenticatedRetainsRoute
  '/_authenticated/routes': typeof AuthenticatedRoutesRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/webhooks': typeof AuthenticatedWebhooksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/bridges/$plugin': typeof AuthenticatedBridgesPluginRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/bridges/': typeof AuthenticatedBridgesIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/plugins/': typeof AuthenticatedPluginsIndexRoute
  '/_authenticated/plugins/$nodeId/$plugin': typeof AuthenticatedPluginsNodeIdPluginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/acl'
    | '/api-keys'
    | '/audit'
    | '/auth-providers'
    | '/auto-subscriptions'
    | '/blacklist'
    | '/broker-config'
    | '/nodes'
    | '/publish'
    | '/retains'
    | '/routes'
    | '/subscriptions'
    | '/users'
    | '/webhooks'
    | '/bridges/$plugin'
    | '/clients/$clientId'
    | '/bridges/'
    | '/clients/'
    | '/plugins/'
    | '/plugins/$nodeId/$plugin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/acl'
    | '/api-keys'
    | '/audit'
    | '/auth-providers'
    | '/auto-subscriptions'
    | '/blacklist'
    | '/broker-config'
    | '/nodes'
    | '/publish'
    | '/retains'
    | '/routes'
    | '/subscriptions'
    | '/users'
    | '/webhooks'
    | '/'
    | '/bridges/$plugin'
    | '/clients/$clientId'
    | '/bridges'
    | '/clients'
    | '/plugins'
    | '/plugins/$nodeId/$plugin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/acl'
    | '/_authenticated/api-keys'
    | '/_authenticated/audit'
    | '/_authenticated/auth-providers'
    | '/_authenticated/auto-subscriptions'
    | '/_authenticated/blacklist'
    | '/_authenticated/broker-config'
    | '/_authenticated/nodes'
    | '/_authenticated/publish'
    | '/_authenticated/retains'
    | '/_authenticated/routes'
    | '/_authenticated/subscriptions'
    | '/_authenticated/users'
    | '/_authenticated/webhooks'
    | '/_authenticated/'
    | '/_authenticated/bridges/$plugin'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/bridges/'
    | '/_authenticated/clients/'
    | '/_authenticated/plugins/'
    | '/_authenticated/plugins/$nodeId/$plugin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/acl': {
      id: '/_authenticated/acl'
      path: '/acl'
      fullPath: '/acl'
      preLoaderRoute: typeof AuthenticatedAclRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys': {
      id: '/_authenticated/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthenticatedApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auth-providers': {
      id: '/_authenticated/auth-providers'
      path: '/auth-providers'
      fullPath: '/auth-providers'
      preLoaderRoute: typeof AuthenticatedAuthProvidersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auto-subscriptions': {
      id: '/_authenticated/auto-subscriptions'
      path: '/auto-subscriptions'
      fullPath: '/auto-subscriptions'
      preLoaderRoute: typeof AuthenticatedAutoSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blacklist': {
      id: '/_authenticated/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof AuthenticatedBlacklistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/broker-config': {
      id: '/_authenticated/broker-config'
      path: '/broker-config'
      fullPath: '/broker-config'
      preLoaderRoute: typeof AuthenticatedBrokerConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nodes': {
      id: '/_authenticated/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AuthenticatedNodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/publish': {
      id: '/_authenticated/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof AuthenticatedPublishRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/retains': {
      id: '/_authenticated/retains'
      path: '/retains'
      fullPath: '/retains'
      preLoaderRoute: typeof AuthenticatedRetainsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routes': {
      id: '/_authenticated/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof AuthenticatedRoutesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/webhooks': {
      id: '/_authenticated/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthenticatedWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bridges/': {
      id: '/_authenticated/bridges/'
      path: '/bridges'
      fullPath: '/bridges/'
      preLoaderRoute: typeof AuthenticatedBridgesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bridges/$plugin': {
      id: '/_authenticated/bridges/$plugin'
      path: '/bridges/$plugin'
      fullPath: '/bridges/$plugin'
      preLoaderRoute: typeof AuthenticatedBridgesPluginRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plugins/': {
      id: '/_authenticated/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof AuthenticatedPluginsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plugins/$nodeId/$plugin': {
      id: '/_authenticated/plugins/$nodeId/$plugin'
      path: '/plugins/$nodeId/$plugin'
      fullPath: '/plugins/$nodeId/$plugin'
      preLoaderRoute: typeof AuthenticatedPluginsNodeIdPluginRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAclRoute: typeof AuthenticatedAclRoute
  AuthenticatedApiKeysRoute: typeof AuthenticatedApiKeysRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedAuthProvidersRoute: typeof AuthenticatedAuthProvidersRoute
  AuthenticatedAutoSubscriptionsRoute: typeof AuthenticatedAutoSubscriptionsRoute
  AuthenticatedBlacklistRoute: typeof AuthenticatedBlacklistRoute
  AuthenticatedBrokerConfigRoute: typeof AuthenticatedBrokerConfigRoute
  AuthenticatedNodesRoute: typeof AuthenticatedNodesRoute
  AuthenticatedPublishRoute: typeof AuthenticatedPublishRoute
  AuthenticatedRetainsRoute: typeof AuthenticatedRetainsRoute
  AuthenticatedRoutesRoute: typeof AuthenticatedRoutesRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWebhooksRoute: typeof AuthenticatedWebhooksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBridgesPluginRoute: typeof AuthenticatedBridgesPluginRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedBridgesIndexRoute: typeof AuthenticatedBridgesIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedPluginsIndexRoute: typeof AuthenticatedPluginsIndexRoute
  AuthenticatedPluginsNodeIdPluginRoute: typeof AuthenticatedPluginsNodeIdPluginRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAclRoute: AuthenticatedAclRoute,
  AuthenticatedApiKeysRoute: AuthenticatedApiKeysRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedAuthProvidersRoute: AuthenticatedAuthProvidersRoute,
  AuthenticatedAutoSubscriptionsRoute: AuthenticatedAutoSubscriptionsRoute,
  AuthenticatedBlacklistRoute: AuthenticatedBlacklistRoute,
  AuthenticatedBrokerConfigRoute: AuthenticatedBrokerConfigRoute,
  AuthenticatedNodesRoute: AuthenticatedNodesRoute,
  AuthenticatedPublishRoute: AuthenticatedPublishRoute,
  AuthenticatedRetainsRoute: AuthenticatedRetainsRoute,
  AuthenticatedRoutesRoute: AuthenticatedRoutesRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWebhooksRoute: AuthenticatedWebhooksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBridgesPluginRoute: AuthenticatedBridgesPluginRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedBridgesIndexRoute: AuthenticatedBridgesIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedPluginsIndexRoute: AuthenticatedPluginsIndexRoute,
  AuthenticatedPluginsNodeIdPluginRoute: AuthenticatedPluginsNodeIdPluginRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
